config/routes.rb
Rails.application.routes.draw do

  devise_for :admins,controllers: {
    sessions:      'admins/sessions',
    passwords:     'admins/passwords',
    registrations: 'admins/registrations'
  }

  devise_for :end_users, controllers: {
    sessions:      'end_users/sessions',
    passwords:     'end_users/passwords',
    registrations: 'end_users/registrations'
  }

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  #ルートでアイテムインデックス記載
  root "items#index"
  #アイテム
  resources :items, only: [:show, :index] do
  #いいね
    resource :likes, only: [:create, :destroy]
  end
  # いいねidを
  resources :likes, only: [:index]
  
  resources :end_users, only: [:new, :edit, :create, :update, :show, :destroy] do
    resources :orders, only: [:new, :create, :update, :index]
    resources :addresses, only: [:new, :edit, :create, :update, :destroy]


  collection do
  get 'change_password'
  patch 'password_update' => 'end_users#password_update', as: 'password_update'
 
  end

  end
  get 'end_users/:end_user_id/orders/confirm/' => "orders#confirm", as:"confirm_end_user_order"
  get "/order/complete" => "orders#complete", as:"complete_order"


resources :admins, only: [:index]

  # get 'end_users/password/change' => 'end_users#change_password', as:'change_password'


  #カートあいてむ
  resources :cart_items, only: [:create, :destroy, :index]
  post "cart_item/count"  => "cart_items#update",as:"cart_item_count"

  #商品管理
  resources :manage_items do
    member do
      get :move_lower
      get :move_higher
      get :restore
    end
  end

  #エンドユーザー管理者
  resources :manage_end_users
  get 'manage_end_users/search' => "manage_end_users#search"

  #注文管理
  resources :manage_orders

  #カテゴリー
  resources :categories, only: [:create, :update]
  delete 'category/destroy' => "categories#destroy", as: 'destroy_category'

  #アーティスト
  resources :artists, only: [:create, :update]
  delete 'artist/destroy' => "artists#destroy", as: 'destroy_artist'

  #レーベル
  resources :labels, only: [:create, :update]
  delete 'label/destroy' => "labels#destroy", as: 'destroy_label'


  # レビュー
  resources :reviews

  #　税率
  resources :taxes, only: [:create, :update, :destroy, :index]
  get 'tax/select' => "taxes#select", as: 'select_tax'

  # 送料
  resources :carriages, only: [:create, :update, :destroy, :index]
  get 'carriage/select' => "carriages#select", as: 'select_carriage'

end

app/models/cart_item.rb
class CartItem < ApplicationRecord

  belongs_to :end_user
  belongs_to :item
  validates :count, :numericality => { :greater_than => 0 }

end

app/controllers/cart_items_controller.rb
class CartItemsController < ApplicationController
	before_action :authenticate_end_user!

	def create
		# 同アイテムがあれば加算・なければNEW
		cart_item = current_end_user.cart_items.find_by(item_id: cart_item_params[:item_id])
		if cart_item.nil?
			cart_item = CartItem.new(cart_item_params)
			if cart_item.item.sales_status == 'on_sale'
				cart_item.end_user_id = current_end_user.id
				cart_item.save
				flash.now[:notice] = "「#{cart_item.item.album}」をカートに追加しました。"
			end
			check_out_of_stock
		else
			cart_item.count += cart_item_params[:count].to_i
			cart_item.save
			flash.now[:notice] = "カート内の「#{cart_item.item.album}」の数量が変更されました。"
			check_out_of_stock
		end
	end

	def destroy
		cart_item = CartItem.find(params[:id])
		cart_item.destroy
		redirect_to cart_items_path, :alert => "カートから商品を削除しました。"
	end

	def update
		@cart_item = CartItem.find(cart_item_params[:id])
		@cart_item.count += cart_item_params[:count].to_i
		# 販売中または在庫が０より小さいとき、削除
		if @cart_item.count <= 0
			@cart_item.destroy
			redirect_to cart_items_path, :alert =>"カートから商品を削除しました。"
		else
			#在庫があるときカートアイテムをセーブし、
			@cart_item.save
			flash.now[:notice] = "カート内の「#{@cart_item.item.album}」の数量が変更されました。"
			check_out_of_stock
			@cart_item = CartItem.find(cart_item_params[:id])
			set_subtotal
			set_total
		end
	end

	def index
		set_subtotal
		set_total
		@cart_items = CartItem.where(end_user_id: current_end_user.id)
		check_out_of_stock
	end

	private
	def cart_item_params
		params.require(:cart_item).permit(:id,:count,:item_id)
	end
end

app/helpers/cart_items_helper.rb
module CartItemsHelper
end

app/views/cart_items/_count.html.erb
<span id="cart-<%= cart_item.id %>">
<table class="pull-right">
    <tbody>
        <td>
            <%= cart_item.count %>
        </td>
        <td style="padding-left:10px;">

            <%= button_to '+', cart_item_count_path(cart_item: {id: cart_item.id,count: 1}),{remote: true, method: :post,class:"btn-xs btn-default",:style=>"width:20px;", :data => {:disable_with => "+"}} %>
        
            <%= button_to '-', cart_item_count_path(cart_item: {id: cart_item.id,count: -1}),{remote: true, method: :post,class:"btn-xs btn-default",:style=>"width:20px;", :data => {:disable_with => "-"}} %>

            <%# remote: true  非同期 %>
        </td>
    </tbody>
</table>
</span>

app/views/cart_items/create.js.erb
$('#cart').html("<%= current_end_user.cart_items.count %>");
$('#messages').html('<%= escape_javascript(render("layouts/flash")) %>');
$('.alert').fadeIn("slow", function () {
	$(this).delay(3000).fadeOut("slow");
});

app/views/cart_items/index.html.erb
<div class = "container">
  <div class = "row">
    <div class="col-sm-8 col-sm-offset-2">
    <h2 class="text-center">お客様のカート</h2>
    <div class="box-radius">

    <% if @cart_items.any? %>

    <table class="table" style="margin-bottom:-10px;">
      <thead><tr><th class="col-xs-3"></th><th class="col-xs-3">商品名</th><th class="col-xs-2 text-right">数量</th><th class="col-xs-2 text-right">税抜価格</th><th class="col-xs-2"></th></tr></thead>
      <tbody>
      
      <% @cart_items.each do |cart_item| %>
        <tr><td><%= attachment_image_tag cart_item.item, :image, :fill, 50,50, fallback: "no_image.jpg", :size=>"50x50",class:"images" %></td>
        <td style="vertical-align:middle;"><%= link_to item_path(cart_item.item) do %><%= cart_item.item.album %><% end %></td>
        <td class="text-right" style="vertical-align:middle;"><%= render 'count', cart_item: cart_item %>
        </td>
        <td class="text-right" style="vertical-align:middle;" id="item-total">¥<%= total_price(cart_item) %></td>
        <td class="text-right" style="vertical-align:middle;"><%= link_to "", cart_item_path(cart_item),{ method: :delete,class:"btn btn-default glyphicon glyphicon-trash",:data => {:disable_with => ""}}%></td></tr>
      <% end %>
      <tr><td colspan="5" class="text-right" id="subtotal">小計　¥<%= @subtotal %></td></tr>
      <tr><td colspan="5" class="text-right" id="cost">+ 消費税　¥<%= @total - @subtotal - carriage_rate%><br>
      + 送料（全国一律）¥<%= carriage_rate %></td></tr>
      <tr><td colspan="5" class="text-right" id="total">
      <strong>合計　¥<%= @total %></strong></td></tr>
      
      </tbody>
    </table>

      <% else %>
        <p class="text-center">カートは空です。</p>
      <% end %>

    </div>

    <div class="text-center">
    <% if @cart_items.any? %>
      <%= link_to "会計に進む", new_end_user_order_path(current_end_user),method: :get, class:"btn btn-default" %>
    <% end %>
    <p style="margin-top:25px;"><%= link_to "トップページ", items_path %></p>
      </div>
    </div>
  </div>
</div>

app/views/cart_items/update.js.erb
$('#cart-<%= @cart_item.id %>').html('<%= escape_javascript(render("cart_items/count", cart_item: @cart_item )) %>');
$('#messages').html('<%= escape_javascript(render("layouts/flash")) %>');
$('#item-total-<%= @cart_item.id %>').html('¥<%= total_price(@cart_item) %>');
$('#subtotal').html('小計　¥<%= @subtotal %>');
$('#cost').html('+ 消費税　¥<%= @total - @subtotal - carriage_rate%><br>+ 送料（全国一律）¥<%= carriage_rate %>');
$('#total').html('<strong>合計　¥<%= @total %></strong>')
<%= render 'layouts/alert'%>