config/routes.rb
Rails.application.routes.draw do

  devise_for :admins,controllers: {
    sessions:      'admins/sessions',
    passwords:     'admins/passwords',
    registrations: 'admins/registrations'
  }

  devise_for :end_users, controllers: {
    sessions:      'end_users/sessions',
    passwords:     'end_users/passwords',
    registrations: 'end_users/registrations'
  }

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  #ルートでアイテムインデックス記載
  root "items#index"
  #アイテム
  resources :items, only: [:show, :index] do
  #いいね
    resource :likes, only: [:create, :destroy]
  end
  # いいねidを
  resources :likes, only: [:index]
  
  resources :end_users, only: [:new, :edit, :create, :update, :show, :destroy] do
    resources :orders, only: [:new, :create, :update, :index]
    resources :addresses, only: [:new, :edit, :create, :update, :destroy]


  collection do
  get 'change_password'
  patch 'password_update' => 'end_users#password_update', as: 'password_update'
 
  end

  end
  get 'end_users/:end_user_id/orders/confirm/' => "orders#confirm", as:"confirm_end_user_order"
  get "/order/complete" => "orders#complete", as:"complete_order"


resources :admins, only: [:index]

  # get 'end_users/password/change' => 'end_users#change_password', as:'change_password'


  #カートあいてむ
  resources :cart_items, only: [:create, :destroy, :index]
  post "cart_item/count"  => "cart_items#update",as:"cart_item_count"

  #商品管理
  resources :manage_items do
    member do
      get :move_lower
      get :move_higher
      get :restore
    end
  end

  #エンドユーザー管理者
  resources :manage_end_users
  get 'manage_end_users/search' => "manage_end_users#search"

  #注文管理
  resources :manage_orders

  #カテゴリー
  resources :categories, only: [:create, :update]
  delete 'category/destroy' => "categories#destroy", as: 'destroy_category'

  #アーティスト
  resources :artists, only: [:create, :update]
  delete 'artist/destroy' => "artists#destroy", as: 'destroy_artist'

  #レーベル
  resources :labels, only: [:create, :update]
  delete 'label/destroy' => "labels#destroy", as: 'destroy_label'


  # レビュー
  resources :reviews

  #　税率
  resources :taxes, only: [:create, :update, :destroy, :index]
  get 'tax/select' => "taxes#select", as: 'select_tax'

  # 送料
  resources :carriages, only: [:create, :update, :destroy, :index]
  get 'carriage/select' => "carriages#select", as: 'select_carriage'

end

app/models/item.rb
class Item < ApplicationRecord

has_many :order_items
has_many :reviews
has_many :likes
has_many :cart_items
has_many :discs

belongs_to :artist
belongs_to :label
belongs_to :category
attachment :image

enum sales_status: [:on_sale,:suspension, :deleted]

# accepts_nested_attributes_for：has_many関連の子レコードをまとめて登録（ネストした関連先のテーブルもまとめて保存）
accepts_nested_attributes_for :discs, allow_destroy: true

validates :album, presence: true, length: { in: 1..30 }
validates :price, presence: true, length: { in: 1..7 }
validates :price, :numericality => { :greater_than => 0 }
validates :stock, presence: true, length: { in: 1..4 }
validates :stock, :numericality => { :greater_than_or_equal_to => 0 }
validates :sales_status, presence: true
validates :category_id, presence: true
validates :label_id, presence: true



# いいね機能
def favorited_by?(end_user)
    likes.where(end_user_id: end_user.id).exists?
end

end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
	def show
		# require "byebug"; byebug
		@item = Item.find(params[:id])
		if @item.sales_status == 'deleted'
			@item = nil
		else
			@reviews = @item.reviews.page(params[:page]).per(3)
			@discs = @item.discs
			if end_user_signed_in?
				if current_end_user.reviews.any?

					@review = current_end_user.reviews.find_by(item_id: @item.id)
					@review = Review.new if @review.nil?
				else
					@review = Review.new
				end
			end
		end
	end

	def index
		@results = @search.result(distinct: true).order(release_date: "DESC").page(params[:page]).per(9)
	end


	def search
	end

	private
	def item_params
		params.require(:end_user).permit(:name, :price, :image)
	end



end

app/helpers/items_helper.rb
module ItemsHelper
end

app/views/items/_deleted.html.erb
<p>該当商品は現在販売しておりません。</p>

app/views/items/index.html.erb
    <div class="container">
<%# 商品詳細ページ遷移リンク %>

        <div class="row">
        
        <%# 検索ワードが空欄以外の時に表示 %>
        <% if params[:q].present? && params[:q][:album_or_artist_name_or_label_name_or_discs_songs_name_cont_any].present? %>
            <p>キーワード：<%= params[:q][:album_or_artist_name_or_label_name_or_discs_songs_name_cont_any] %>での検索結果 <%= @results.total_count %>件</p>
        <% else %>
            <h2 style="margin-left:50px;">新着商品</h2>
        <% end %>

        <% if @results.any? %>

        <%# 検索対象一覧 %>
            <% @results.each do |results| %>
            <%= link_to (item_path(results)) do %>
            <!-- ジャケット写真 -->
            <div class="col-xs-12 col-sm-4">
                <div class="item-box">
                    <div class="row">
                        <div class="col-xs-6 col-sm-12">
                            <div class="image-box">
                                <%= attachment_image_tag results, :image, :fill, 200, 200, fallback: "no_image.jpg", :size=>"200x200" %>
                            </div>
                        </div>
                        <div class="col-xs-6 col-sm-12">
                                <%# 商品名 %>
                                <p style="font-weight:bold;"><%= results.album %></p>
                                <%# アーティスト名 %>
                                <p><%= results.artist.name %></p>
                                <%# 価格 %>
                                <p><span style="color:red;">¥<%= tax_calc(results.price) %></span>(税込)</p>
                                <%# 販売ステータス %>
                                <p><%= stock_check(results) %></p>
                        </div>
                    </div>
                </div>
            </div>
            <% end %><%# リンク %>
            <% end %><%# resultsのEND %>
                <div class="col-xs-12 col-sm-12 text-center"><%= paginate @results %></div>
            <% else %><%# result.any? ヒットしなかった時 %>
            <p>該当する商品は見つかりませんでした。</p>
            <p class="text-center"><%= link_to "トップページ",items_path %></p>
            <% end %><%# results.any? %>
        </div>

    </div>




<!-- ページャー -->

app/views/items/search.html.erb
<h2>商品検索結果</h2>
<div class="container">
    <div class="row">
        <div class="col-xs-9">
            <table class="table table-hover table-inverse">
                <!-- 商品検索結果 -->
                <tbody>
                    <tr>
                        <%= @items.each do|item| %>
                        <td>
                        <%= attachment_image_tag item, :image, :fill, 10, 10, class: "pull-left profile-thumb", size:"20x20"%>
                        </td>
                        <td>
                        <p><%= item.name %></p>
                        <p><%= item.artist %></p>
                        <p><%= item.label %></p>
                        <p><%= item.album %></p>
                        <p><%= item.stack %></p>
                        </td>
                        <% end %>
                        <td>
                        <p>価格</p>
                        <p>¥<%= item.price %>(税込)</p>
                        </td>
                    </tr>
                </tbody>
            </table>
        </div>
    </div>
</div>

app/views/items/show.html.erb
<div class="container">
    <div class="row">
<% if !@item.nil?%>
        <%# ジャケ写 %>
        <div class="col-sm-6 text-center">
            <div class="image-box">
                <%= attachment_image_tag @item, :image, :fill, 215, 215, fallback: "no_image.jpg", :size=>"215x215", class: "images" %>
            </div>
        </div>

        <%# 商品詳細情報 %>
        <div class="col-sm-6 text-center">
            <div style="margin:25px 0;">

                    <%# 商品名 %>
                    <div class="row">
                        <table class="col-xs-8 col-xs-offset-2">
                            <tbody>
                                <td class="text-center" style="padding-right:10px;width:60%;">
                                <h2 style="display:inline;" class="glyphicon glyphicon-cd"><%= @item.album %></h2>
                                </td>
                                <%# いいねカウント %>
                                <%# @itemsをrenderのcollectionでそれぞれを取り出してitemとして渡す %>
                                <td class="text-left col-xs-3" style="padding-left:10px;width:25%;">
                                    <%= render 'likes/like_links', item: @item %>
                                </td>
                            </tbody>
                        </table>
                    </div>
                    <%# アーティスト名 %>
                    <p style="margin:30px 0 20px 0;"><%= @item.artist.name %> / <%= @item.label.name %> / <%= @item.category.name %></p>

                    <%# 価格 %>

                    <span style="font-size:1.4em;display:inline-block;color:red;">¥<%= tax_calc(@item.price) %><span style="color:black;">(税込)</span>　</span><%= stock_check(@item) %>
                    <%# 在庫ステータス %>

                    <%# カートに入れる %>

                    <% if end_user_signed_in? && @item.sales_status == 'on_sale' && @item.stock >= 1 %>
                        <%= form_with model: CartItem.new do |f| %>
                        <%= f.select :count, options_for_select((1..20).to_a), {}, class: "form-control", :style=>"width:50px;display:inline-block;margin-top:20px;" %>
                        <%= f.hidden_field :item_id, :value => @item.id %>
                        <%= f.submit "カートに追加", class: "btn btn-default", :style=>"display:inline-block;margin-left:15px;", :data => {:disable_with => "カートに追加"} %>
                        <% end %>
                    <% end%>
            </div>
        </div>

    </div><%# rowクラス閉じタグ %>

<p></p>

    <div class="row">
        <%# 収録曲 %>
        <div class="col-sm-6">
            <div class="box">

            <h4><strong class="glyphicon glyphicon-music">収録曲</strong></h4>
                <% @discs.each do |disc| %>
                <table class="table table-striped table-responsive">
                    <thead>
                        <tr>
                            <th width="10%">曲順</th>
                            <th width="45%">曲名</th>
                            <th width="45%">アーティスト名</th>
                        </tr>
                    </thead>
                    <tbody>
                    <% disc.songs.each do |song| %>
                        <tr>
                            <td>
                                No.<%= song.position %>
                            </td>
                            <td>
                                <%= song.name %>
                            </td>
                            <td>
                                <%= song.artist.name %>
                            </td>
                        </tr>
                    <% end %>
                    </tbody>
                </table>
                <% end %>
            </div>
        </div>

        <%# レビュー %>
        <div class="col-sm-6">
            <%# レビュー内容表示 %>
            <div class="box-radius">

            <h4><strong class="glyphicon glyphicon-comment">レビュー</strong></h4>
                <table class="table table-responsive">
                    <tbody>
                    <% if @reviews.any? %>
                    <% @reviews.each do |review| %>
                    <tr>
                        <td>
                            <p>投稿者：
                                <%= review.name %>
                                <% if end_user_signed_in?%>
                                    <% if review.end_user_id == current_end_user.id%>
                                <%= link_to "", review_path(review),method: :delete,class:"btn btn-danger glyphicon glyphicon-trash pull-right",:data => {:disable_with => ""}%>
                                    <% end %>
                                <% end %>
                            </p>
                            <p>
                                <%# ヘルパーメソッド使用 %>
                                <%= simple_date(review.created_at) %>
                            </p>
                            <%# 投稿コメント %>
                            <p>
                                <%= review.comment %>
                            </p>
                        </td>
                    </tr>
                    <%end%>
                    <%else%>
                    <tr><td>レビューはまだありません。</td></tr>
                    <% end %>
                    <td class="text-center"><%= paginate @reviews %></td>


                    </tbody>
                </table>


            <%# レビュー投稿 %>
            <% if end_user_signed_in? %>
            <h4 class="glyphicon glyphicon-pencil" style="margin-top:-10px;">新規投稿・編集</h4>
            <div class="item-rev-edit">

                <%= form_for @review do |f| %>
                    <p>名前</p>
                    <%= f.text_field :name,class:"form-control" ,placeholder:"ニックネームを入力"%>
                    <p>レビュー</p>
                    <%= f.text_area :comment,class:"form-control",placeholder:"レビューを入力（投稿は商品につき１件まで可能です。）" %>
                    <p></p>
                    <%# hidden_fieldで情報を渡す %>
                    <%= f.hidden_field :item_id, :value => @item.id %>
                    <%= f.submit("レビューする",class: 'btn btn-primary center-block ') %>
                <% end %>
            </div>
            <% end %>
            </div>

        </div>

<%else%>
<%= render 'deleted'%>
<%end%>


    </div><%# rowクラス閉じタグ %>







</div><%# containerクラス閉じタグ %>








</div>