config/routes.rb
Rails.application.routes.draw do

  devise_for :admins,controllers: {
    sessions:      'admins/sessions',
    passwords:     'admins/passwords',
    registrations: 'admins/registrations'
  }

  devise_for :end_users, controllers: {
    sessions:      'end_users/sessions',
    passwords:     'end_users/passwords',
    registrations: 'end_users/registrations'
  }

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  #ルートでアイテムインデックス記載
  root "items#index"
  #アイテム
  resources :items, only: [:show, :index] do
  #いいね
    resource :likes, only: [:create, :destroy]
  end
  # いいねidを
  resources :likes, only: [:index]
  
  resources :end_users, only: [:new, :edit, :create, :update, :show, :destroy] do
    resources :orders, only: [:new, :create, :update, :index]
    resources :addresses, only: [:new, :edit, :create, :update, :destroy]


  collection do
  get 'change_password'
  patch 'password_update' => 'end_users#password_update', as: 'password_update'
 
  end

  end
  get 'end_users/:end_user_id/orders/confirm/' => "orders#confirm", as:"confirm_end_user_order"
  get "/order/complete" => "orders#complete", as:"complete_order"


resources :admins, only: [:index]

  # get 'end_users/password/change' => 'end_users#change_password', as:'change_password'


  #カートあいてむ
  resources :cart_items, only: [:create, :destroy, :index]
  post "cart_item/count"  => "cart_items#update",as:"cart_item_count"

  #商品管理
  resources :manage_items do
    member do
      get :move_lower
      get :move_higher
      get :restore
    end
  end

  #エンドユーザー管理者
  resources :manage_end_users
  get 'manage_end_users/search' => "manage_end_users#search"

  #注文管理
  resources :manage_orders

  #カテゴリー
  resources :categories, only: [:create, :update]
  delete 'category/destroy' => "categories#destroy", as: 'destroy_category'

  #アーティスト
  resources :artists, only: [:create, :update]
  delete 'artist/destroy' => "artists#destroy", as: 'destroy_artist'

  #レーベル
  resources :labels, only: [:create, :update]
  delete 'label/destroy' => "labels#destroy", as: 'destroy_label'


  # レビュー
  resources :reviews

  #　税率
  resources :taxes, only: [:create, :update, :destroy, :index]
  get 'tax/select' => "taxes#select", as: 'select_tax'

  # 送料
  resources :carriages, only: [:create, :update, :destroy, :index]
  get 'carriage/select' => "carriages#select", as: 'select_carriage'

end

app/models/tax.rb
class Tax < ApplicationRecord
    enum valid_flag: [:off ,:on]
    before_destroy :must_not_destroy
    validates :rate, presence: true
    validates :rate, :numericality => { :greater_than => 1 }
    def must_not_destroy
        throw(:abort) if self.valid_flag == 'on'
    end
end

app/controllers/taxes_controller.rb
class TaxesController < ApplicationController
  before_action :authenticate_admin!
  def index
    @tax = Tax.new
    @taxes = Tax.all.order(rate: "ASC")
  end
  def create
    tax = Tax.new(tax_params)
    if tax.rate.between?(1,100)
      tax.rate = (tax.rate / 100) + 1
      tax.valid_flag = 'off'
      tax.save
      redirect_to taxes_path, :notice => "税率を登録しました。"
    else
      render :index
    end
  end
  def select
    taxes = Tax.all
    tax = Tax.find_by(id: params[:id])
    if !tax.nil? && tax.valid_flag == 'off'
      ActiveRecord::Base.transaction do
        taxes.each do |tax|
          tax.valid_flag = "off"
          tax.save
        end
        tax.valid_flag = "on"
        tax.save
      end
      redirect_to taxes_path, :notice => "税率設定を変更しました。"
    else
      redirect_to taxes_path
    end
  end
  def destroy
    tax = Tax.find(params[:id])
    tax.destroy
    redirect_to taxes_path
  end
  private
  def tax_params
    params.require(:tax).permit(:rate)
  end
end

app/helpers/taxes_helper.rb
module TaxesHelper
end

app/views/taxes/index.html.erb
<div class="container">
  <div class="row">
<%# <!-- sidebar  ここから --> %>
    <div class="col-sm-3">
    <%= render "layouts/adminsidebar" %>
    </div>
<%# <!-- sidebar  ここまで --> %>
    <div class="col-sm-9">
      <h2>税率管理</h2>
      <div class="box">
      <h4>税率選択</h4>
<div class="form-box">
    <%= form_with url: {:controller=>"taxes",:action=>"select"},method: :get,local: true do |f| %>
    <table class="table table-hover">
        <tbody>
        <% @taxes.each do |tax| %>
            <tr>
                <td>
            <%if tax.valid_flag == 'on'%>
                <label class="valid"><%= f.radio_button :id, tax.id, :checked=>"checked" %><%= (tax.rate - 1) * 100 %>%</label><span style="color:red;">選択中</span><br>
            <% else %>
                <label><%= f.radio_button :id, tax.id %><%= (tax.rate - 1) * 100 %>%</label>
                <%= link_to "", tax_path(tax),method: :delete,class:"pull-right glyphicon glyphicon-trash btn btn-default" %><br>
            <% end %>
                
                </td>
            </tr>
        <% end %>
            </tbody>
        </table>
        <%= f.submit "選択",class: "btn btn-default" , :data => {:disable_with => "選択"}%>
    <% end %>
</div>
    <div class="form-box">
    <h4>税率の数値を追加</h4>
    <%= form_with model: @tax do |f| %>
        <%= f.text_field :rate, class: "form-control pull-left", :style=>"width:20%;",placeholder:"1〜100(%)" %>
        <%= f.submit "登録",class:"btn btn-default",:style=>"width:10%;", :data => {:disable_with => "登録"}%>
    <% end %>
    </div>
      </div>
    </div>
  </div>
</div>