config/routes.rb
Rails.application.routes.draw do

  devise_for :admins,controllers: {
    sessions:      'admins/sessions',
    passwords:     'admins/passwords',
    registrations: 'admins/registrations'
  }

  devise_for :end_users, controllers: {
    sessions:      'end_users/sessions',
    passwords:     'end_users/passwords',
    registrations: 'end_users/registrations'
  }

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  #ルートでアイテムインデックス記載
  root "items#index"
  #アイテム
  resources :items, only: [:show, :index] do
  #いいね
    resource :likes, only: [:create, :destroy]
  end
  # いいねidを
  resources :likes, only: [:index]
  
  resources :end_users, only: [:new, :edit, :create, :update, :show, :destroy] do
    resources :orders, only: [:new, :create, :update, :index]
    resources :addresses, only: [:new, :edit, :create, :update, :destroy]


  collection do
  get 'change_password'
  patch 'password_update' => 'end_users#password_update', as: 'password_update'
 
  end

  end
  get 'end_users/:end_user_id/orders/confirm/' => "orders#confirm", as:"confirm_end_user_order"
  get "/order/complete" => "orders#complete", as:"complete_order"


resources :admins, only: [:index]

  # get 'end_users/password/change' => 'end_users#change_password', as:'change_password'


  #カートあいてむ
  resources :cart_items, only: [:create, :destroy, :index]
  post "cart_item/count"  => "cart_items#update",as:"cart_item_count"

  #商品管理
  resources :manage_items do
    member do
      get :move_lower
      get :move_higher
      get :restore
    end
  end

  #エンドユーザー管理者
  resources :manage_end_users
  get 'manage_end_users/search' => "manage_end_users#search"

  #注文管理
  resources :manage_orders

  #カテゴリー
  resources :categories, only: [:create, :update]
  delete 'category/destroy' => "categories#destroy", as: 'destroy_category'

  #アーティスト
  resources :artists, only: [:create, :update]
  delete 'artist/destroy' => "artists#destroy", as: 'destroy_artist'

  #レーベル
  resources :labels, only: [:create, :update]
  delete 'label/destroy' => "labels#destroy", as: 'destroy_label'


  # レビュー
  resources :reviews

  #　税率
  resources :taxes, only: [:create, :update, :destroy, :index]
  get 'tax/select' => "taxes#select", as: 'select_tax'

  # 送料
  resources :carriages, only: [:create, :update, :destroy, :index]
  get 'carriage/select' => "carriages#select", as: 'select_carriage'

end

app/controllers/manage_end_users_controller.rb
class ManageEndUsersController < ApplicationController

	# before_action :authenticate_admin!

	before_action :authenticate_admin!
	

	def show
		@end_user = EndUser.find(params[:id])
		@orders = Order.where(end_user_id: params[:id]).order(created_at: :desc).page(params[:page]).per(5)
	end

	def destroy
		@end_user = EndUser.find(params[:id])
		@end_user.destroy
		redirect_to manage_end_users_path
	end

	def update
		@end_user = EndUser.find(params[:id])
		if @end_user.update(end_user_params)
			redirect_to manage_end_user_path(@end_user)
		else
		   render :edit
		end
	end

	def index
		@end_user = EndUser.all
		@results = @search_user.result(distinct: true)
    end

	def search
		# 検索フォームで取得したパラメーターをモデルに渡す
		# @search = EndUser.search(params{search})
	end

	def edit
		@end_user = EndUser.find(params[:id])
	end
end


	private
    def end_user_params
		 params.require(:end_user).permit(:last_name, :first_name, :last_kana, :first_kana, :postal_code, :address, :phone_number, :email)
    end

app/helpers/manage_end_users_helper.rb
module ManageEndUsersHelper
end

app/views/manage_end_users/_search.html.erb
<h3>ユーザー検索</h3>
<%= search_form_for @search_user, url: manage_end_users_path do |f| %>
<div class="form-box">
    <%= f.search_field :last_name_or_first_name_or_last_kana_or_first_kana_cont_any, class: "form-control pull-left", :style=>"width: 67%;", placeholder: "ユーザー名で検索" %>
    <%= f.submit '検索', class: "btn btn-default", :style=> "width:33%;" %>
</div>

<% end %>

app/views/manage_end_users/edit.html.erb
  <div class="container">
    <div class="row">
      <div class="col-md-8 col-md-offset-2">
          <h2>ユーザー情報編集ページ</h2>
            <%= form_for @end_user, url: manage_end_user_path do |f| %>
              <div class="box">

                <div class="row form-group name-form">
                  <div class="item"><%= f.label :氏名 %></div>
                  <div class="col-md-10 form name-form"><%= f.text_field :last_name, :size=>"25", autofocus: true, class:"form-inline", placeholder:"姓" %>
                  <%= f.text_field :first_name, :size=>"25", autofocus: true, class:"form-inline", placeholder:"名"%></div>
                </div>

                <div class="row form-group">
                  <div class="item"><%= f.label :氏名%><i>(カナ)</i></div>
                  <div class="col-md-10"><%= f.text_field :last_kana, :size=>"25", autofocus: true, class:"form-inline", placeholder:"セイ" %>
                  <%= f.text_field :first_kana, :size=>"25", autofocus: true, class:"form-inline", placeholder:"メイ"%></div>
                </div>

                <div class="row form-group">
                  <div class="item"><%= f.label :郵便番号 %></div>
                  <div class="col-md-10"><%= f.text_field :postal_code, autofocus: true, class:"form-control", placeholder:"ハイフンなし" %></div>
                </div>

                <div class="row form-group">
                  <div class="item"><%= f.label :住所 %></div>
                  <div class="col-md-10"><%= f.text_field :address, autofocus: true, class:"form-control" %></div>
                </div>

                <div class="row form-group">
                  <div class="item"><%= f.label :電話番号 %></div>
                  <div class="col-md-10"><%= f.text_field :phone_number, autofocus: true, class:"form-control", placeholder:"ハイフンなし" %></div>
                </div>

                <div class="row form-group">
                  <div class="item"><%= f.label :メールアドレス %></div>
                  <div class="col-md-10"><%= f.email_field :email, class:"form-control" %></div>
                </div>

                <div class="text-center">
                  <%= f.submit "更新する", class:"btn btn-primary btn-block" %>
                </div>
              <% end %>

              <div class="link"><%= link_to "戻る", manage_end_user_path(@end_user.id) %></div>

            </div>
      </div>
    </div>
  </div>

app/views/manage_end_users/index.html.erb
<div class="container">
    <div class="row">
    
<!-- sidebar  ここから -->
    <div class="col-sm-3">
      <%= render "layouts/adminsidebar" %>
      <div class="side-box">
        <%= render "search" %>
      </div>
    </div>
<!-- sidebar  ここまで -->
<% if @results.any? %>
      <div class="col-sm-9">
        <h2>ユーザー一覧</h2>
        <table class="table table-striped table-responsive">
          <thead>
            <tr>
              <th><strong>ユーザー名</strong></th>
              <th><strong>電話番号</strong></th>
              <th><strong>住所</strong></th>
              <th></th>

            </tr>
          </thead>
          <tbody>
          <% if @param_q == 1 %>
            <% @end_user.each do |f| %>
              <tr>
                <td><%= f.last_name %> <%= f.first_name %></td>
                <td><%= f.phone_number %></td>
                <td><%= f.address.truncate(25) %></td>
                <td><%= link_to "詳細", manage_end_user_path(f.id), class: "btn btn-primary"%></td>
              </tr>
            <% end %>
          <% else %>
            <% @results.each do |f| %>
              <tr>
                <td><%= f.last_name %> <%= f.first_name %></td>
                <td><%= f.phone_number %></td>
                <td><%= f.address.truncate(25) %></td>
                <td><%= link_to "詳細", manage_end_user_path(f.id), class: "btn btn-primary"%></td>
              </tr>
            <% end %>
          <% end %>
          </tbody>
        </table>
      </div>
      <% else %>
         <p><%= "該当の検索結果はありませんでした。" %></p>
      <% end %>
    </div>
</div>

app/views/manage_end_users/show.html.erb
<div class="container">
    <div class="row">
    <!-- sidebar  ここから -->
        <div class="col-sm-3">
            <%= render "layouts/adminsidebar" %>
            <div class="side-box">
                <%= render "search" %>
            </div>
        </div>
    <!-- sidebar  ここまで -->


        <div class="col-xs-9">
            <h2><strong>
                <%= @end_user.last_name %>
                <%= @end_user.first_name %>
                </strong> さん
            </h2>
            <div class="box">
                <div class="row form-box">
                    <div class="col-xs-2"><label>姓</label></div>
                    <div class="col-xs-10"><%= @end_user.last_name %></div>
                </div>
                <div class="row form-box">
                    <div class="col-xs-2"><label>名</label></div>
                    <div class="col-xs-10"><%= @end_user.first_name %></div>
                </div>
                <div class="row form-box">
                    <div class="col-xs-2"><label>カナ（姓）</label></div>
                    <div class="col-xs-10"><%= @end_user.last_kana %></div>
                </div>
                <div class="row form-box">
                    <div class="col-xs-2"><label>カナ（名）</label></div>
                    <div class="col-xs-10"><%= @end_user.first_kana %></div>
                </div>
                <div class="row form-box">
                    <div class="col-xs-2"><label>パスワード</label></div>
                    <div class="col-xs-10"><%= @end_user.encrypted_password = "●●●●" %></div>
                </div>
                <div class="row form-box">
                    <div class="col-xs-2"><label>メールアドレス</label></div>
                    <div class="col-xs-10"><%= @end_user.email %></div>
                </div>
                <div class="row form-box">
                    <div class="col-xs-2"><label>電話番号</label></div>
                    <div class="col-xs-10"><%= @end_user.phone_number %></div>
                </div>
                <div class="row form-box">
                    <div class="col-xs-2"><label>郵便番号</label></div>
                    <div class="col-xs-10">〒<%= postal_code(@end_user.postal_code) %></div>
                </div>
                <div class="row form-box">
                    <div class="col-xs-2"><label>住所</label></div>
                    <div class="col-xs-10"><%= @end_user.address %></div>
                </div>

                <div class="row form-box">
                    <%= link_to "編集", edit_manage_end_user_path(@end_user.id), class: "btn btn-primary pull-right", :style=>"width: 10%;" %>
                </div>

                <div class="row form-box">
                    <%= link_to "退会", manage_end_user_path(@end_user), method: :delete , class: "btn btn-primary pull-right", :style=>"width: 10%;", data: { confirm: "本当に退会させますか？"}%>
                </div>
            </div><%# box %>

            <%# 注文履歴 %>
            <div class="box">

            <%# 購入履歴部分テンプレート %>
            <%= render 'orders/history', orders: @orders %>